CREATE DATABASE bd_is;
USE bd_is;

CREATE TABLE PARTICIPANTES (
  id_p INT(8) PRIMARY KEY,
  nombre_p VARCHAR(64) NOT NULL,
  mail_p VARCHAR(64) NOT NULL,
  contrasena_p VARCHAR(64) NOT NULL
);

CREATE TABLE COORD_CURSOS (
  id_cc INT(8) PRIMARY KEY,
  nombre_cc VARCHAR(64) NOT NULL,
  mail_cc VARCHAR(64) NOT NULL,
  contrasena_cc VARCHAR(64) NOT NULL
);

CREATE TABLE COORD_RECURSOS (
  id_cr INT(8) PRIMARY KEY,
  nombre_cr VARCHAR(64) NOT NULL,
  mail_cr VARCHAR(64) NOT NULL,
  contrasena_cr VARCHAR(64) NOT NULL
);

CREATE TABLE CURSOS (
  id_curso INT(8) PRIMARY KEY,
  fecha_inicio DATE NOT NULL,
  fecha_final DATE NOT NULL,
  max_inscripciones INT(8) NOT NULL,
  ponente VARCHAR(64) NOT NULL,
  descripcion VARCHAR(64) NOT NULL,
  aula VARCHAR(64) NOT NULL,
  id_cc INT(8) NOT NULL,
  id_p INT(8) NOT NULL
);

CREATE TABLE RECURSOS (
  recurso VARCHAR(64) PRIMARY KEY,
  id_curso INT(8) NOT NULL,
  id_cr INT(8) NOT NULL
);

CREATE TABLE PARTICIPANTES_CURSOS (
  PARTICIPANTES_id_p INT(8),
  CURSOS_id_curso INT(8),
  PRIMARY KEY (PARTICIPANTES_id_p, CURSOS_id_curso)
);

ALTER TABLE PARTICIPANTES_CURSOS ADD FOREIGN KEY (PARTICIPANTES_id_p) REFERENCES PARTICIPANTES (id_p);

ALTER TABLE PARTICIPANTES_CURSOS ADD FOREIGN KEY (CURSOS_id_curso) REFERENCES CURSOS (id_curso);

ALTER TABLE CURSOS ADD CONSTRAINT fk_coord_cursos_cursos FOREIGN KEY (id_cc) REFERENCES COORD_CURSOS (id_cc);

ALTER TABLE RECURSOS ADD CONSTRAINT fk_cursos_recursos FOREIGN KEY (id_curso) REFERENCES CURSOS (id_curso);

ALTER TABLE RECURSOS ADD CONSTRAINT fk_coord_recursos_recursos FOREIGN KEY (id_cr) REFERENCES COORD_RECURSOS (id_cr);